### PR TITLE
fix: wrong scaling

### PR DESCRIPTION
**Pull request by jobo322**
with this we are able to run an optimization with negative peaks

image

### CODE REVIEW

**Comment by jobo322** [comment]
it is pending to fix when the spectrum is scaled all in negative values

**Comment by jobo322** [comment]
the result for the same data shifted -2

image

**Comment by jobo322** [comment]
but the current behavior is still not correct because we does not returns what should be the baseline for the shape, so the reconstructed spectrum is wrong

image

**Comment by lpatiny** [comment]
@jobo322 Could you delete this branch if it will really not be used anymore.

**Pull request closed without merging**
